name: Go
on: [pull_request]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.12
      uses: actions/setup-go@v1
      with:
        go-version: 1.12
      id: go

    - uses: actions/checkout@master
    - name: Unit Test
      run: $GITHUB_WORKSPACE/scripts/unit.sh
